# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3b9c5ad9cd2ac54ed6617cf32ce82d877f0d7cbd8e07e0e5852ae84e481349bd3778a48d0bcdff0882854f7d604982a5b1e4dfec302db8bc637215d847b265

test:
  secret_key_base: 485950bafac66da5a91340c258da4d8708fde45d355b8004ab573b3c9bf964a51aaf57a09813e7175971bc1eb140e13c79cae41b89b61b4f5fc402463c3a00e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
